version: '3'
services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: 0033:0033
    ports:
      - "8080:80"
    volumes:
      - /cloud/:/srv
      - /webservice/filebrowser/filebrowser.db:/database.db
    restart: on-failure
  ethercalc:
    image: audreyt/ethercalc
    container_name: ethercalc
    ports:
      - "80:8000"
    environment:
      REDIS_PORT_6379_TCP_ADDR: redis
      REDIS_PORT_6379_TCP_PORT: 6379
    links:
      - redis:redis
    restart: always
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - /var/lib/redis:/data
    command: redis-server --appendonly yes
    restart: always
  etherpad:
    image: etherpad/etherpad
    container_name: etherpad
    ports:
      - "9001:9001"
    restart: always
    volumes:
      - .:/etherpad/
