apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: ethercalc
  name: ethercalc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ethercalc
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: ethercalc
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      containers:
        - env:
            - name: REDIS_PORT_6379_TCP_ADDR
              value: redis
            - name: REDIS_PORT_6379_TCP_PORT
              value: "6379"
          image: audreyt/ethercalc
          name: ethercalc
          ports:
            - containerPort: 8000
          resources: {}
      affinity:
              nodeAffinity:
                      preferredDuringSchedulingIgnoredDuringExecution:
                              - weight: 2
                                preference:
                                      matchExpressions:
                                              - key: kubernetes.io/hostname
                                                operator: In
                                                values:
                                                        - kslave-1
                              - weight: 1
                                preference:
                                      matchExpressions:
                                              - key: kubernetes.io/hostname
                                                operator: In
                                                values:
                                                        - kslave-2
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: ethercalc
  name: ethercalc
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8000
  selector:
    io.kompose.service: ethercalc
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: etherpad
  name: etherpad
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: etherpad
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: etherpad
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      containers:
        - image: etherpad/etherpad
          name: etherpad
          ports:
            - containerPort: 9001
          resources: {}
      affinity:
              nodeAffinity:
                      preferredDuringSchedulingIgnoredDuringExecution:
                              - weight: 2
                                preference:
                                      matchExpressions:
                                              - key: kubernetes.io/hostname
                                                operator: In
                                                values:
                                                        - kslave-1
                              - weight: 1
                                preference:
                                      matchExpressions:
                                              - key: kubernetes.io/hostname
                                                operator: In
                                                values:
                                                        - kslave-2
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: etherpad
  name: etherpad
spec:
  ports:
    - name: "9001"
      port: 9001
      targetPort: 9001
  selector:
    io.kompose.service: etherpad
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: file-browser
  name: file-browser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-browser
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: file-browser
    spec:
      containers:
      - image: filebrowser/filebrowser
        name: file-browser
        ports:
           - containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: file-browser
  name: file-browser
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    app: file-browser
status:
  loadBalancer: {}
---
